"""add xp ledger

Revision ID: 0d125f4ce94f
Revises: 4c7ee757fed2
Create Date: 2026-08-13 12:38:07.449984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d125f4ce94f'
down_revision: Union[str, Sequence[str], None] = '4c7ee757fed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_ledger_student_id'), 'xp_ledger', ['student_id'], unique=False)
    op.create_index(op.f('ix_xp_ledger_tenant_id'), 'xp_ledger', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_ledger_tenant_id'), table_name='xp_ledger')
    op.drop_index(op.f('ix_xp_ledger_student_id'), table_name='xp_ledger')
    op.drop_table('xp_ledger')
    # ### end Alembic commands ###
