"""stuck flags

Revision ID: 17280a99fab3
Revises: bef6e1b27a4e
Create Date: 2026-08-16 09:47:54.611359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17280a99fab3'
down_revision: Union[str, Sequence[str], None] = 'bef6e1b27a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stuck_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stuck_flags_created_at'), 'stuck_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_stuck_flags_student_id'), 'stuck_flags', ['student_id'], unique=False)
    op.create_index(op.f('ix_stuck_flags_tenant_id'), 'stuck_flags', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Created after 7b3a32e71a94 enabled row level security, so that migration's
    # TENANT_TABLES list cannot cover it -- the policy goes on here instead,
    # exactly as consent_records and safety_events do.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('ALTER TABLE stuck_flags ENABLE ROW LEVEL SECURITY')
        op.execute('ALTER TABLE stuck_flags FORCE ROW LEVEL SECURITY')
        op.execute(
            "CREATE POLICY tenant_isolation ON stuck_flags "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::int)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP POLICY IF EXISTS tenant_isolation ON stuck_flags')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stuck_flags_tenant_id'), table_name='stuck_flags')
    op.drop_index(op.f('ix_stuck_flags_student_id'), table_name='stuck_flags')
    op.drop_index(op.f('ix_stuck_flags_created_at'), table_name='stuck_flags')
    op.drop_table('stuck_flags')
    # ### end Alembic commands ###
