"""coppa consent records

Revision ID: 30d936a23517
Revises: 7b3a32e71a94
Create Date: 2026-08-13 18:00:32.518320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d936a23517'
down_revision: Union[str, Sequence[str], None] = '7b3a32e71a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_tenant_id'), 'consent_records', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('refresh_token_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

    # consent_records is tenant-scoped and was created after 7b3a32e71a94, so
    # it needs the same RLS backstop or it would be the one table without one.
    # `timestamp` is server_default CURRENT_TIMESTAMP here rather than now():
    # autogenerate ran against SQLite. Both resolve to the transaction clock on
    # Postgres, so it is left as emitted.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('ALTER TABLE consent_records ENABLE ROW LEVEL SECURITY')
        op.execute('ALTER TABLE consent_records FORCE ROW LEVEL SECURITY')
        op.execute(
            "CREATE POLICY tenant_isolation ON consent_records "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::int)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP POLICY IF EXISTS tenant_isolation ON consent_records')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_id')
    op.drop_index(op.f('ix_consent_records_tenant_id'), table_name='consent_records')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
