"""remove chat server defaults

Revision ID: 4c7ee757fed2
Revises: 99bd8a562d1a
Create Date: 2026-08-13 12:09:22.977319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7ee757fed2'
down_revision: Union[str, Sequence[str], None] = '99bd8a562d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Batch mode: SQLite cannot ALTER COLUMN, so alembic rebuilds the table.
    # On Postgres this emits plain ALTER ... DROP DEFAULT.
    with op.batch_alter_table('chat_history') as batch_op:
        batch_op.alter_column('student_id',
                   existing_type=sa.INTEGER(),
                   server_default=None,
                   existing_nullable=False)
        batch_op.alter_column('session_id',
                   existing_type=sa.VARCHAR(length=64),
                   server_default=None,
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history') as batch_op:
        batch_op.alter_column('session_id',
                   existing_type=sa.VARCHAR(length=64),
                   server_default=sa.text("'default_session'"),
                   existing_nullable=False)
        batch_op.alter_column('student_id',
                   existing_type=sa.INTEGER(),
                   server_default=sa.text("'2'"),
                   existing_nullable=False)
    # ### end Alembic commands ###
