"""template instance split

Revision ID: 5a7513143add
Revises: 0d125f4ce94f
Create Date: 2026-08-13 17:01:20.484256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7513143add'
down_revision: Union[str, Sequence[str], None] = '0d125f4ce94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subject_area', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_url', sa.String(), nullable=False),
    sa.Column('ufa_eligible', sa.Boolean(), nullable=False),
    sa.Column('color_hex', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_tenant_id'), 'programs', ['tenant_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('week_start', sa.Integer(), nullable=False),
    sa.Column('week_end', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_tenant_id'), 'units', ['tenant_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('resource_url', sa.String(), nullable=False),
    sa.Column('resource_path', sa.String(), nullable=False),
    sa.Column('workbook_pages', sa.String(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('school_day_offset', sa.Integer(), nullable=True),
    sa.Column('day_of_week_hint', sa.Integer(), nullable=True),
    sa.Column('dependency_mode', sa.String(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('is_boss_fight', sa.Boolean(), nullable=False),
    sa.Column('medium', sa.String(), nullable=False),
    sa.Column('ufa_eligible', sa.Boolean(), nullable=False),
    sa.Column('ufa_hours_credit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_tenant_id'), 'lessons', ['tenant_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('focus_minutes', sa.Integer(), nullable=False),
    sa.Column('completion_notes', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uix_student_lesson')
    )
    op.create_index(op.f('ix_assignments_lesson_id'), 'assignments', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_assignments_student_id'), 'assignments', ['student_id'], unique=False)
    op.create_index(op.f('ix_assignments_tenant_id'), 'assignments', ['tenant_id'], unique=False)
    # Drop children before parents. Autogenerate emitted courses before
    # modules, which SQLite tolerates (FK enforcement is off by default) but
    # Postgres rejects — modules.course_id still references courses.
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_modules_tenant_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Parents before children — autogenerate emitted modules first, but
    # modules.course_id references courses, which would not exist yet.
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('subject_area', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=False),
    sa.Column('platform_url', sa.VARCHAR(), nullable=False),
    sa.Column('ufa_eligible', sa.BOOLEAN(), nullable=False),
    sa.Column('color_hex', sa.VARCHAR(), nullable=False),
    sa.Column('emoji', sa.VARCHAR(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('week_start', sa.INTEGER(), nullable=False),
    sa.Column('week_end', sa.INTEGER(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_tenant_id'), 'modules', ['tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('module_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(), nullable=False),
    sa.Column('resource_url', sa.VARCHAR(), nullable=False),
    sa.Column('resource_path', sa.VARCHAR(), nullable=False),
    sa.Column('workbook_pages', sa.VARCHAR(), nullable=False),
    sa.Column('sequence_order', sa.INTEGER(), nullable=False),
    sa.Column('school_day_offset', sa.INTEGER(), nullable=True),
    sa.Column('scheduled_date', sa.DATE(), nullable=True),
    sa.Column('day_of_week_hint', sa.INTEGER(), nullable=True),
    sa.Column('dependency_mode', sa.VARCHAR(), nullable=False),
    sa.Column('estimated_minutes', sa.INTEGER(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('actual_completion_date', sa.DATE(), nullable=True),
    sa.Column('completion_notes', sa.VARCHAR(), nullable=False),
    sa.Column('focus_minutes', sa.INTEGER(), nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), nullable=False),
    sa.Column('is_boss_fight', sa.BOOLEAN(), nullable=False),
    sa.Column('medium', sa.VARCHAR(), nullable=False),
    sa.Column('ufa_eligible', sa.BOOLEAN(), nullable=False),
    sa.Column('ufa_hours_credit', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_assignments_tenant_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_student_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_lesson_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_lessons_tenant_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_units_tenant_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_programs_tenant_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
