"""add tenant_id and chat constraints

Revision ID: 99bd8a562d1a
Revises: ac64f65df2d1
Create Date: 2026-08-13 12:01:30.393660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bd8a562d1a'
down_revision: Union[str, Sequence[str], None] = 'ac64f65df2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_app_config_tenant_id'), 'app_config', ['tenant_id'], unique=False)
    # Batch mode so this works on SQLite (which cannot ALTER COLUMN or add a
    # constraint in place) as well as Postgres. The FK is named explicitly —
    # an anonymous constraint cannot be dropped again on downgrade.
    # `type_=sa.String(64)` is stated outright because autogenerate ran against
    # SQLite, where VARCHAR and VARCHAR(64) are indistinguishable.
    with op.batch_alter_table('chat_history') as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), server_default='2', nullable=False))
        batch_op.alter_column('session_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.String(length=64),
                   server_default='default_session',
                   existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_chat_history_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_chat_history_student_id_users', 'users', ['student_id'], ['id'])
    op.add_column('courses', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.add_column('creator_projects', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_creator_projects_tenant_id'), 'creator_projects', ['tenant_id'], unique=False)
    op.add_column('expenses', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    op.add_column('modules', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_modules_tenant_id'), 'modules', ['tenant_id'], unique=False)
    op.add_column('purchases', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_purchases_tenant_id'), 'purchases', ['tenant_id'], unique=False)
    op.add_column('rewards', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_rewards_tenant_id'), 'rewards', ['tenant_id'], unique=False)
    op.add_column('school_calendar', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_school_calendar_tenant_id'), 'school_calendar', ['tenant_id'], unique=False)
    op.add_column('school_events', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_school_events_tenant_id'), 'school_events', ['tenant_id'], unique=False)
    op.add_column('tasks', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_column('tasks', 'tenant_id')
    op.drop_index(op.f('ix_school_events_tenant_id'), table_name='school_events')
    op.drop_column('school_events', 'tenant_id')
    op.drop_index(op.f('ix_school_calendar_tenant_id'), table_name='school_calendar')
    op.drop_column('school_calendar', 'tenant_id')
    op.drop_index(op.f('ix_rewards_tenant_id'), table_name='rewards')
    op.drop_column('rewards', 'tenant_id')
    op.drop_index(op.f('ix_purchases_tenant_id'), table_name='purchases')
    op.drop_column('purchases', 'tenant_id')
    op.drop_index(op.f('ix_modules_tenant_id'), table_name='modules')
    op.drop_column('modules', 'tenant_id')
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_column('expenses', 'tenant_id')
    op.drop_index(op.f('ix_creator_projects_tenant_id'), table_name='creator_projects')
    op.drop_column('creator_projects', 'tenant_id')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_column('courses', 'tenant_id')
    with op.batch_alter_table('chat_history') as batch_op:
        batch_op.drop_constraint('fk_chat_history_student_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_history_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_history_student_id'))
        batch_op.drop_index(batch_op.f('ix_chat_history_session_id'))
        batch_op.alter_column('session_id',
                   existing_type=sa.String(length=64),
                   type_=sa.VARCHAR(),
                   server_default=None,
                   existing_nullable=False)
        batch_op.drop_column('student_id')
        batch_op.drop_column('tenant_id')
    op.drop_index(op.f('ix_app_config_tenant_id'), table_name='app_config')
    op.drop_column('app_config', 'tenant_id')
    # ### end Alembic commands ###
