"""add reward is_active

Revision ID: ac64f65df2d1
Revises: 35a5f30bc810
Create Date: 2026-08-13 11:54:06.601592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac64f65df2d1'
down_revision: Union[str, Sequence[str], None] = '35a5f30bc810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'is_active')
    # ### end Alembic commands ###
