"""safety events

Alerts raised when the AI tutor's safety check trips on a child's message.

Like consent_records, this table is created after 7b3a32e71a94 enabled row
level security, so that migration's TENANT_TABLES list cannot cover it. The
policy is applied inline below instead. Any future tenant-scoped table needs
the same treatment -- reading the constant alone will tell you the coverage is
complete when it is not.

Revision ID: bef6e1b27a4e
Revises: 30d936a23517
Create Date: 2026-08-16 08:04:23.312688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef6e1b27a4e'
down_revision: Union[str, Sequence[str], None] = '30d936a23517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('excerpt', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_created_at'), 'safety_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_safety_events_student_id'), 'safety_events', ['student_id'], unique=False)
    op.create_index(op.f('ix_safety_events_tenant_id'), 'safety_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Same predicate as every other tenant table. Applied here rather than in
    # 7b3a32e71a94 because that migration ran before this table existed.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('ALTER TABLE safety_events ENABLE ROW LEVEL SECURITY')
        op.execute('ALTER TABLE safety_events FORCE ROW LEVEL SECURITY')
        op.execute(
            "CREATE POLICY tenant_isolation ON safety_events "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::int)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP POLICY IF EXISTS tenant_isolation ON safety_events')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_events_tenant_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_student_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_created_at'), table_name='safety_events')
    op.drop_table('safety_events')
    # ### end Alembic commands ###
