"""add user is_active

Revision ID: cd43933858c0
Revises: 5a7513143add
Create Date: 2026-08-13 17:12:00.364275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd43933858c0'
down_revision: Union[str, Sequence[str], None] = '5a7513143add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # sa.true() rather than a literal: autogenerate ran against SQLite and
    # emitted sa.text('1'), which becomes a bare `DEFAULT 1` — an integer
    # expression against a boolean column, which Postgres rejects. sa.true()
    # compiles per dialect (`true` on Postgres, `1` on SQLite) and matches the
    # model's server_default=true(), so alembic check stays clean on both.
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
