"""
Rebuild the 2026-27 Flokus Academy calendar.

WHY THIS EXISTS
---------------
The original v1 calendar was generated by laying 677 tasks onto 180 consecutive
Mon-Fri days starting 2026-08-17. That produced three defects that only show up
once you look at the whole year at once:

  1. ZERO BREAKS. School ran straight through Thanksgiving, Christmas Day and
     New Year's Day. 16 holiday days carried work, including 3 tasks on Dec 25.

  2. MATH STOPPED IN NOVEMBER. All 60 Beast Academy lessons were front-loaded
     into weeks 1-15. From 2026-11-27 to 2027-04-23 -- 21 weeks -- the only math
     left was the Friday review routine. The Level 2 sprint was intentional, but
     nothing was authored to follow it.

  3. FRIDAY WAS INDISTINGUISHABLE FROM A CORE DAY. Mon-Thu are the core school
     days; Friday is review, book parties and catch-up. The data already
     reflected that (Friday only ever held review routines) but nothing
     enforced it, so any future scheduling pass could quietly put new
     curriculum there.

This script rebuilds the calendar from the existing task rows. It does not
invent curriculum except where explicitly noted (Beast Academy Level 3, which
is authored in beast_level3.py).

THE MODEL
---------
Every task in v1 belongs to a STREAM, and every stream owns a fixed weekday
slot. That was verified against the original data: all 30 streams were 100%
weekday-consistent across 677 rows, so this is a description of the existing
design, not a new constraint imposed on it.

Two kinds of stream, and they are NOT rescheduled the same way:

  ROUTINE  a weekly habit -- "Chess - Tactics & Play" every Wednesday. A routine
           is a SLOT, not a sequence. If a week has no Wednesday, that week has
           no chess tactics session, and nothing is owed. You do not make up a
           habit. So routines are regenerated to fit the calendar and their
           counts drop naturally across holidays.

  LESSON   content that progresses -- Beast chapter 7, Tuttle Vol 2 Ch 3, Dart 4
           reading week 2. A lesson sequence must be delivered in full and in
           order. Lessons cascade forward across a holiday rather than being
           dropped or doubled up.

Getting this distinction wrong is what produced the original bug: the generator
treated a habit and a chapter as the same kind of object, so it had to keep the
day count fixed at 180, which is why no breaks could exist.
"""

import sqlite3
import re
import shutil
from datetime import date, timedelta
from collections import defaultdict

from beast_level3 import LEVEL3_TASKS, LEVEL2_CAPSTONE_RENAMES
import free_market_rules
import curriculum_io

DB = "flokus.db"

# The calendar itself lives in school_year.py so the curriculum importer works
# off the same definition -- an importer with its own idea of which days are
# school days is how work ends up scheduled on Christmas.
from school_year import (MON, TUE, WED, THU, FRI, YEAR_START,
                         INSTRUCTIONAL_WEEKS, BREAK_WEEKS, HOLIDAYS,
                         build_calendar)


def slots_for(school_days, weekday):
    """Every school day falling on `weekday`, in order. This is the list of
    openings a stream owning that weekday can be laid onto."""
    return [d for d in school_days if d.weekday() == weekday]


def week_index(day, week_starts):
    """Which instructional week `day` belongs to, 0-based."""
    for i, monday in enumerate(week_starts):
        if monday <= day <= monday + timedelta(days=4):
            return i
    raise ValueError(day)


# Streams whose every item refers back to a lesson in another stream. They are
# placed last, one at a time, each taking the first free slot strictly after
# the lesson it names.
# Streams placed later must not land on a Friday another showcase already owns.
# Both sides sort earlier than the key, so they are always placed first.
AVOID_SHARING_A_DAY = {
    "lesson::tt_yearend": ("lesson::dart_party", "lesson::crunch_expo"),
}

FOLLOWER_STREAMS = ("lesson::tt_civics", "lesson::crit_exercises")
PARENT_PREFIXES = ("Tuttle Twins Civics & Discussion (", "Chapter Exercises (")


def parent_of(title):
    """The lesson a follower refers to, or None if it stands alone."""
    for prefix in PARENT_PREFIXES:
        if title.startswith(prefix):
            return title[len(prefix):].rstrip(")")
    return None


def group_key(stream_key, title):
    """Lessons sharing a group key share a single day. Returns None when a
    lesson stands alone, which is every stream except the book parties."""
    if stream_key == "lesson::dart_party":
        m = re.search(r"Dart (\d+)", title)
        return f"dart{m.group(1)}" if m else None
    if stream_key == "lesson::tt_yearend":
        # "History Timeline" and its discussion are one Friday.
        return parent_of(title) or title
    return None


# The v1 plan this script reads was laid out from Mon 17 Aug 2026 -- the
# placeholder start, before school's real first day was known. That date is a
# fact about the OLD data and must not follow school_year.FIRST_DAY when the
# real start moves, or every stream's cadence would be re-read against the
# wrong origin and silently shift.
LEGACY_V1_START = date(2026, 8, 17)


def original_week(day):
    """Which week of the ORIGINAL v1 calendar a task sat in. The original ran
    36 unbroken Mon-Fri weeks from LEGACY_V1_START, so this is plain
    arithmetic."""
    return (day - LEGACY_V1_START).days // 7


# ---------------------------------------------------------------------------
# Stream classification
# ---------------------------------------------------------------------------
# (stream_key, kind, weekday). kind is "routine" or "lesson".
# Order matters: the first matching rule wins.

# Brilliant.org is retired. Its rows are dropped rather than rescheduled: it was
# a routine (a twice-weekly habit slot), not a course with a sequence to finish,
# so there is no progress to preserve. Its Tue/Thu slots go to economics.
RETIRED_CATEGORIES = {"Logic (Brilliant.org)"}


def classify(category, title):
    t = title.strip()

    # --- routines: weekly habits, regenerated to fit the calendar -----------
    ROUTINES = {
        ("Logic (Chess.com)", "Chess — Skill Focus (rotating)"): MON,
        ("Logic (Chess.com)", "Chess — Tactics & Play"): WED,
        ("Logic (Chess.com)", "Chess — Weekly Challenge & Matches"): FRI,
        ("Language Arts (Brave Writer)", "Creative Freewrite & Discussion"): TUE,
        ("Language Arts (Brave Writer)", "Reverse Dictation & Grammar"): WED,
        ("Language Arts (Brave Writer)", "Big Juicy Questions & Reading"): THU,
        ("Language Arts (Brave Writer)",
         "Brave Writer & History Review / Poetry Teatime"): FRI,
        ("Logic (Brilliant.org)", "Brilliant — Topic Focus (rotating)"): TUE,
        ("Logic (Brilliant.org)", "Brilliant — Interactive Practice"): THU,
        ("Science (Outschool)", "Outschool — Live Class"): TUE,
        ("Science (CrunchLabs)", "Applied STEM / Project Tinkering"): THU,
        ("Math (Beast Academy)",
         "Beast Academy & Brilliant Weekly Math Review"): FRI,
    }
    if (category, t) in ROUTINES:
        return (f"routine::{category}::{t}", "routine", ROUTINES[(category, t)])

    # --- lessons: ordered content that must all be delivered ---------------
    if category == "Math (Beast Academy)":
        # Beast is one of two streams that span all four core days.
        return ("lesson::beast", "lesson", None)

    if category == free_market_rules.CATEGORY:
        return ("lesson::economics", "lesson", None)

    if category == "Language Arts (Brave Writer)":
        if re.match(r"^Dart \d+: .*— read ", t):
            return ("lesson::dart_reading", "lesson", MON)
        # WHY Friday: the Book Party prep activity and the party itself are one
        # event. Keeping them on the same Friday frees nine Mondays for reading
        # weeks and makes the celebration read as a celebration, not homework.
        if t.startswith("👑 Dart Book Party") or t.endswith("(Book Party)"):
            return ("lesson::dart_party", "lesson", FRI)

    TT_YEAR_END = ("Tuttle Series Synthesis", "History Timeline",
                   "History & Logic Annual Portfolios")

    if category == "Social Studies (Tuttle Twins)":
        if t.startswith("Tuttle Twins Civics & Discussion"):
            # The three year-end discussions belong WITH the piece they discuss,
            # on the same Friday. Left on Wednesdays they had to be scheduled
            # after a Friday parent, which pushed them into the following week
            # and ran the stream off the end of the calendar.
            if parent_of(t) in TT_YEAR_END:
                return ("lesson::tt_yearend", "lesson", FRI)
            return ("lesson::tt_civics", "lesson", WED)
        # WHY Friday: year-end synthesis IS review work, and Friday is the
        # review day. Moving these three off Monday is also what makes the
        # Tuttle chapter sequence fit around the three Monday federal holidays.
        if t in TT_YEAR_END:
            return ("lesson::tt_yearend", "lesson", FRI)
        return ("lesson::tt_chapter", "lesson", MON)

    if category == "Logic (Critical Thinking Co.)":
        if t.startswith("Chapter Exercises"):
            return ("lesson::crit_exercises", "lesson", THU)
        return ("lesson::crit_chapter", "lesson", TUE)

    if category == "Science (CrunchLabs)":
        if t.startswith("👑 Master Expo"):
            return ("lesson::crunch_expo", "lesson", FRI)
        return ("lesson::crunch_box", "lesson", THU)

    raise ValueError(f"unclassified task: {category!r} / {title!r}")


# ---------------------------------------------------------------------------
# Rebuild
# ---------------------------------------------------------------------------

def main():
    shutil.copy(DB, DB + ".pre-rebuild-backup")
    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    rows = list(cur.execute(
        "SELECT id, title, category, task_date, video_url, xp_reward, "
        "is_completed, is_boss_fight, medium FROM tasks ORDER BY task_date, id"))

    school_days, week_starts = build_calendar()
    print(f"Calendar: {week_starts[0]} .. "
          f"{week_starts[-1] + timedelta(days=4)}  "
          f"({INSTRUCTIONAL_WEEKS} weeks, {len(school_days)} school days)")

    streams = defaultdict(list)
    dropped = 0
    for r in rows:
        _id, title, cat, _d, vid, xp, done, _boss, med = r
        if cat in RETIRED_CATEGORIES:
            dropped += 1
            continue
        key, kind, weekday = classify(cat, title)
        streams[key].append(dict(id=_id, title=title, category=cat,
                                 video_url=vid, xp=xp, done=done, medium=med,
                                 kind=kind, weekday=weekday, stream=key,
                                 week=original_week(date.fromisoformat(_d))))
    if dropped:
        print(f"  dropped {dropped} rows from retired programs: "
              f"{', '.join(sorted(RETIRED_CATEGORIES))}")

    # --- 1. Beast Academy: Level 2 sprint, then Level 3 at a normal pace ----
    #
    # WHY: Rocky is deliberately accelerating through Level 2 as a foundations
    # catch-up. That was never the bug. The bug was that nothing followed it,
    # so math went dark from December to April. Level 3 is appended here so the
    # math stream runs continuously to the last week of the year.
    beast = streams["lesson::beast"]
    for old, new in LEVEL2_CAPSTONE_RENAMES.items():
        for task in beast:
            if task["title"] == old:
                task["title"] = new
    beast.extend(dict(title=t["title"], category="Math (Beast Academy)",
                      video_url=None, xp=t["xp"], done=0, medium="Offline",
                      kind="lesson", weekday=None, id=None, week=None,
                      stream="lesson::beast", new=True)
                 for t in LEVEL3_TASKS)

    # The Friday math review named a platform that no longer exists in the plan.
    for key, tasks in streams.items():
        for t in tasks:
            if t["title"] == "Beast Academy & Brilliant Weekly Math Review":
                t["title"] = "Beast Academy Weekly Math Review"

    # --- 1b. Free Market Rules: the economics course ------------------------
    #
    # WHY IT IS A LESSON STREAM AND NOT A ROUTINE: the 30 units build on each
    # other -- scarcity before trade-offs, money before inflation, firms before
    # monopoly -- so the order has to survive a holiday, which is exactly what
    # the lesson path guarantees and the routine path does not.
    #
    # It spans all four core days like Beast, one lesson per day. 120 lessons
    # into 144 Mon-Thu openings means it finishes a few weeks before the year
    # ends, which is the right way round: better to land early and have room
    # for the last units to breathe than to run out of calendar in May.
    streams["lesson::economics"] = [
        dict(title=t["title"], category=t["category"], video_url="",
             xp=t["xp"], done=0, medium="Offline", kind="lesson",
             weekday=None, id=None, week=None,
             stream="lesson::economics", new=True)
        for t in free_market_rules.TASKS
    ]

    # --- 2. Critical Thinking: disambiguate the repeated chapters ----------
    #
    # WHY: eight chapters were each scheduled twice under an identical title.
    # Stretching a chapter over two sittings is fine; showing a nine-year-old
    # the same words twice and expecting him to know they mean different pages
    # is not. Naming the parts costs nothing and removes the ambiguity.
    for key in ("lesson::crit_chapter", "lesson::crit_exercises"):
        seen = defaultdict(int)
        totals = defaultdict(int)
        for t in streams[key]:
            totals[t["title"]] += 1
        for t in streams[key]:
            if totals[t["title"]] > 1:
                seen[t["title"]] += 1
                base, n = t["title"], seen[t["title"]]
                t["title"] = (f"{base[:-1]} — Part {n})" if base.endswith(")")
                              else f"{base} — Part {n}")

    # --- 3. Lay every stream onto its slots --------------------------------
    placements = []          # (task, date)
    overflow = []

    # Some streams only make sense after another one has started. The Tuttle
    # civics discussion is ABOUT the chapter read on Monday; the Critical
    # Thinking exercises are the practice FOR the chapter read on Tuesday.
    #
    # This never mattered while the year began on a Monday. Starting on
    # Wednesday 19 Aug removes week one's Monday and Tuesday, so the leaders
    # slid to week two while the followers -- whose weekdays do exist in week
    # one -- stayed put. The result was Sonny discussing Tuttle Chapter 1 five
    # days before reading it, and doing the Critical Thinking exercises for a
    # chapter he had not opened.
    # Constraining only the START of a follower stream is not enough. Labor Day
    # removes a Monday, so every Tuttle chapter after it shifts a week later
    # while the Wednesday discussions do not -- and the pairing stays broken for
    # the rest of the year. 25 of 33 discussions landed before their chapter.
    #
    # So followers are placed LAST and individually: each one takes the first
    # free slot strictly after the lesson it refers to, which it names in its
    # own title -- "Tuttle Twins Civics & Discussion (TT Vol 1 Ch 3)".
    # (follower streams are placed after the leaders, further down)

    # Leaders first; followers need to know where their parent landed.
    ordered_keys = ([k for k in sorted(streams) if k not in FOLLOWER_STREAMS]
                    + [k for k in sorted(streams) if k in FOLLOWER_STREAMS])

    for key in ordered_keys:
        tasks = streams[key]
        kind = tasks[0]["kind"]
        weekday = tasks[0]["weekday"]

        if key in FOLLOWER_STREAMS:
            placed = {t["title"]: d for t, d in placements}
            free = slots_for(school_days, weekday)
            used, late = set(), 0
            for task in tasks:
                parent = parent_of(task["title"])
                after = placed.get(parent) if parent else None
                slot = next((d for d in free
                             if d not in used and (after is None or d > after)),
                            None)
                if slot is None:
                    overflow.append(task)
                    continue
                if after is not None and week_index(slot, week_starts) > \
                        week_index(after, week_starts):
                    late += 1
                used.add(slot)
                placements.append((task, slot))
            days = sorted(used)
            print(f"  follows  {key:<62} {len(tasks):>3} items, "
                  f"{days[0]} .. {days[-1]}"
                  + (f", {late} pushed to a later week than their chapter"
                     if late else ""))
            continue

        if key in ("lesson::beast", "lesson::economics"):
            # The two streams that run every core day. They do not compete for
            # openings -- a Tuesday holds one of each -- so both get the full
            # Mon-Thu list.
            slots = [d for d in school_days if d.weekday() in (MON, TUE, WED, THU)]
        else:
            slots = slots_for(school_days, weekday)
            # Don't stack the showcase days. The Tuttle year-end pieces, the
            # final book party and the CrunchLabs Master Expo are each a
            # celebration Friday; landing two on one day pushed those Fridays
            # to six assignments and turned the best days of the year into the
            # heaviest. Give them a Friday each.
            if key in AVOID_SHARING_A_DAY:
                taken = {d for t, d in placements
                         if t["stream"] in AVOID_SHARING_A_DAY[key]}
                slots = [d for d in slots if d not in taken]

        if kind == "routine":
            # A routine fills every opening it has. Its count is an output of
            # the calendar, not an input to it.
            for slot in slots:
                placements.append((tasks[0], slot))
            print(f"  routine  {key[9:]:<62} {len(slots):>3} occurrences")

        elif key in ("lesson::beast", "lesson::economics", "lesson::tt_chapter"):
            # The dense streams -- a plain consecutive fill, no cadence to
            # preserve. Beast and economics want every core day; the Tuttle
            # chapters want every Monday.
            #
            # WHY TUTTLE IS HERE AND NOT IN THE WEEK-INDEX PATH BELOW: it is a
            # continuous one-a-week sequence, so preserving the week each
            # chapter was originally authored into buys nothing and costs a
            # great deal. Every lost Monday -- the short first week plus three
            # federal holidays -- pushed the whole stream a week later, so the
            # last chapter landed in the final week of the year and the
            # discussion that belongs after it had nowhere to go. Packed
            # densely it finishes with room to spare.
            for task, slot in zip(tasks, slots):
                placements.append((task, slot))
            overflow.extend(tasks[len(slots):])
            print(f"  lesson   {key:<62} {len(tasks):>3} items "
                  f"/ {len(slots)} slots, ends {slots[len(tasks)-1]}"
                  if len(tasks) <= len(slots) else
                  f"  LESSON   {key:<62} ** {len(tasks)-len(slots)} OVERFLOW **")

        else:
            # WHY THIS IS NOT A SIMPLE ZIP: most lesson streams are sparse and
            # periodic, not continuous. Book parties land every fourth week;
            # CrunchLabs boxes every fourth Thursday; the Tuttle synthesis
            # pieces belong in the final weeks. Zipping them onto the first N
            # openings collapses that cadence -- it put all nine book parties in
            # the first nine weeks and the year-end synthesis in September.
            #
            # So each lesson keeps the WEEK it was authored into, and only
            # slides forward when a holiday has removed the day it wanted.
            # A slide cascades through the rest of the stream, which is what
            # keeps the sequence intact instead of doubling two lessons up.
            # Some lessons are two rows describing one sitting -- the Brave
            # Writer Book Party activity and the celebration that follows it
            # are the same Friday afternoon. Group those so the pair consumes
            # one slot between them instead of landing a week apart.
            groups = []
            for task in tasks:
                gk = group_key(key, task["title"])
                if groups and gk is not None and groups[-1][0] == gk:
                    groups[-1][1].append(task)
                else:
                    groups.append((gk, [task]))

            cursor = 0
            slid = 0
            placed_days = []
            for _gk, group in groups:
                want = min(t["week"] for t in group)
                while (cursor < len(slots)
                       and week_index(slots[cursor], week_starts) < want):
                    cursor += 1
                if cursor >= len(slots):
                    overflow.extend(group)
                    continue
                got = week_index(slots[cursor], week_starts)
                if got > want:
                    slid += 1
                for task in group:
                    placements.append((task, slots[cursor]))
                placed_days.append(slots[cursor])
                cursor += 1
            note = f", {slid} slid past a holiday" if slid else ""
            print(f"  lesson   {key:<62} {len(tasks):>3} items, "
                  f"{placed_days[0]} .. {placed_days[-1]}{note}")

    if overflow:
        raise SystemExit(f"\nABORT: {len(overflow)} lessons have no slot. "
                         "Increase INSTRUCTIONAL_WEEKS.")

    # --- 3b. A routine yields its slot to the lesson that replaces it ------
    #
    # WHY: a CrunchLabs Build Day IS that week's applied STEM session, and a
    # Book Party IS that week's Brave Writer Friday. Running the habit and the
    # event on the same day was what pushed eleven days to six tasks -- it read
    # as a punishment for the weeks that were supposed to be the fun ones.
    SUPPRESS = {
        "Applied STEM / Project Tinkering": "lesson::crunch_box",
        "Brave Writer & History Review / Poetry Teatime": "lesson::dart_party",
    }
    lesson_days = defaultdict(set)
    for task, day in placements:
        lesson_days[task.get("stream")].add(day)
    for routine_title, lesson_stream in SUPPRESS.items():
        blocked = lesson_days[lesson_stream]
        before = len(placements)
        placements = [(t, d) for t, d in placements
                      if not (t["title"] == routine_title and d in blocked)]
        print(f"  suppressed {before - len(placements):>2}x "
              f"{routine_title!r} on {lesson_stream[8:]} days")

    # --- 4. Write ----------------------------------------------------------
    # WHY EVERY ROW GETS A source_key HERE:
    # the importer recognises an existing assignment by source_key. Rows written
    # without one are invisible to it, so the first re-import of a program that
    # this script generated added a second complete copy of it -- 120 economics
    # lessons became 240 -- and only settled down from the import after that.
    # Stamping the same key the importer and exporter compute makes a
    # rebuilt schedule and an imported one the same kind of thing.
    curriculum_io._ensure_source_key_column(cur)
    cur.execute("DELETE FROM tasks")
    cur.execute("DELETE FROM sqlite_sequence WHERE name='tasks'")
    for task, day in sorted(placements, key=lambda p: (p[1], p[0]["category"])):
        program = curriculum_io.CATEGORY_TO_PROGRAM.get(
            task["category"], task["category"])
        if task["kind"] == "routine":
            skey = curriculum_io.routine_source_key(program, task["title"], day)
        else:
            skey = curriculum_io.make_source_key(program, "", task["title"])
        cur.execute(
            "INSERT INTO tasks (title, category, task_date, video_url, "
            "xp_reward, is_completed, is_boss_fight, task_summary, "
            "focus_minutes, actual_completion_date, medium, source_key) "
            "VALUES (?,?,?,?,?,?,0,'',0,'',?,?)",
            (task["title"], task["category"], day.isoformat(),
             task["video_url"], task["xp"], task["done"], task["medium"], skey))

    # --- 4b. video_url must hold a video, or nothing ------------------------
    #
    # WHY: sixteen rows carried a platform homepage here (beastacademy.com/login,
    # bravewriter.com, tuttletwins.com). The student card feeds this column
    # straight to st.video(), which renders a non-video URL as an empty black
    # player with a dead scrubber -- the card read as broken and the platform
    # link it should have shown never rendered. Those URLs are also redundant:
    # config.PLATFORM_LINKS already maps every subject to its platform.
    VIDEO_HOSTS = ("youtube.com", "youtu.be", "vimeo.com", ".mp4", ".webm", ".mov")
    cleared = cur.execute(
        "UPDATE tasks SET video_url = '' WHERE video_url IS NOT NULL "
        "AND video_url != '' AND " + " AND ".join(
            f"video_url NOT LIKE '%{h}%'" for h in VIDEO_HOSTS)).rowcount
    print(f"  cleared {cleared} non-video URLs out of video_url")

    # --- 5. Put the breaks on the calendar page ----------------------------
    #
    # WHY: a break that exists only as an absence of tasks is invisible. Sonny
    # should be able to open the calendar and SEE that Thanksgiving week is off.
    cur.execute("DELETE FROM school_events WHERE category = '🌴 Break / Holiday'")
    for start, name in sorted(BREAK_WEEKS.items()):
        cur.execute(
            "INSERT INTO school_events (title, event_date, event_time, category,"
            " importance, reminder_days, description) VALUES (?,?,'',?,?,?,?)",
            (f"🌴 {name} — no school this week", start.isoformat(),
             "🌴 Break / Holiday", "Important", 3,
             f"{name}: {start:%b %d} – {start + timedelta(days=4):%b %d}. "
             "No assignments scheduled."))
    for day, name in sorted(HOLIDAYS.items()):
        cur.execute(
            "INSERT INTO school_events (title, event_date, event_time, category,"
            " importance, reminder_days, description) VALUES (?,?,'',?,?,?,?)",
            (f"🌴 {name} — no school", day.isoformat(), "🌴 Break / Holiday",
             "Normal", 2, f"{name}. Day off — no assignments scheduled."))

    # The "First Day of School" event predates the real start date being known
    # and still pointed at Mon 17 Aug. A calendar that disagrees with the
    # schedule is worse than no calendar entry at all.
    cur.execute(
        "UPDATE school_events SET event_date = ? "
        "WHERE category = '🎓 School Start / Term' AND title LIKE '%First Day%'",
        (school_days[0].isoformat(),))

    last_day = school_days[-1]
    cur.execute(
        "INSERT INTO school_events (title, event_date, event_time, category,"
        " importance, reminder_days, description) VALUES (?,?,'',?,?,?,?)",
        ("🎓 Last Day of School — 5th Grade Complete!", last_day.isoformat(),
         "🎓 School Start / Term", "Important", 7,
         "Final day of the 2026-27 year."))

    # Record the school-week shape in config so nothing later has to guess it.
    cur.execute("INSERT OR REPLACE INTO app_config (key, value) "
                "VALUES ('core_school_days', 'Mon,Tue,Wed,Thu')")
    cur.execute("INSERT OR REPLACE INTO app_config (key, value) "
                "VALUES ('review_day', 'Fri')")

    conn.commit()
    conn.close()
    print(f"\nWrote {len(placements)} tasks. Year ends {last_day}.")


if __name__ == "__main__":
    main()
